export { default as Hero } from "./hero";
export { default as Brands } from "./brands";
export { default as Categories } from "./categories";
export { default as Banners } from "./banners";
export { default as FeaturedProducts } from "./featured-products";
export { default as BestDeal } from "./best-deal";
export { default as OnSaleProducts } from "./on-sale-products";
export { default as Testimonials } from "./testimonials";
export { default as TestimonialsCarousel } from "./testimonials-carousel";
